# Site settings
title: Humainable. 
description: "A site about Humane and Sustainable Foods and Products. Copyright &#169; 2018 Proti.st"
url: "http://humainable.org"
author:
  name: "Proti.st"
  url: "http://proti.st"

# Build settings
baseurl: "/"
markdown: kramdown
remote_theme: KingFelix/emerald

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Custom variables
version: "1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
